### ISSUE TITLE
Authentication issue

### ISSUE THREAD

**Issue by sebasjunca** [newAM/hisensetv_hass#3]
Hi all! 

I've ben looking for a way to control my Hisense TV from homekit (via home assistant), I manage to install hisensetv_hass via HACS, but can't make the authentication step. The switch works for turning on the tv, but it doesn't turn off.

I'm running Home Assistant on RPI Raspbian.

First I tried to execute the installation manually within the homeassistant folder, but then I got this error. Then I tried from the home folder of the pi and got the same issue.

pi@raspberrypi:/home/homeassistant/.homeassistant $ sudo -H python3.8 -m pip install hisensetv

sudo: python3.8: command not found

pi@raspberrypi:/home/homeassistant/.homeassistant $ sudo pip install hisensetv
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting hisensetv
  Could not find a version that satisfies the requirement hisensetv (from versions: )
No matching distribution found for hisensetv

Finally, I installed it with HACS, but as I mentioned above, the authentication command:

pip install hisensetv
hisensetv 10.0.0.28 --authorize

Gets this error:

-bash: hisensetv: command not found

I don't know if this is what is missing in order to turn off or via Home Assistant switch.

I'm new in RPI and Home Assistant, sorry about that.

Cheers all!

**Comment by sebasjunca** [comment]
I have finally added to my RPI (The problem was due to the python version), but the auth code never appears on the TV sand therefore it shows a timeout error.  I tried also from a mac and it works fine (both authentication and commands), so I'm assuming it is related to the RPI 3 model b+, which is odd

here's the error:

hisensetv 192.168.1.33 --authorize
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/hisensetv/__init__.py", line 181, in _wait_for_response
    return self._queue.get(block=True, timeout=self.timeout)
  File "/usr/lib/python3.7/queue.py", line 178, in get
    raise Empty
_queue.Empty

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/pi/.local/bin/hisensetv", line 10, in <module>
    sys.exit(main())
  File "/home/pi/.local/lib/python3.7/site-packages/hisensetv/__main__.py", line 50, in main
    tv.start_authorization()
  File "/home/pi/.local/lib/python3.7/site-packages/hisensetv/__init__.py", line 55, in wrapper
    return func(self, *args, **kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/hisensetv/__init__.py", line 422, in start_authorization
    self._wait_for_response()
  File "/home/pi/.local/lib/python3.7/site-packages/hisensetv/__init__.py", line 185, in _wait_for_response
    ) from e
hisensetv.HisenseTvTimeoutError: failed to recieve a response in 10.000s

I don't know if this repo is maintained or outdated, but making it work on a RPI and HASS would be ideal. Cheers!

**Comment by newAM** [comment]
Are you able to run this command (in a separate process) and let me know what it says when running `hisensetv 192.168.1.33 --authorize` at the same time?
```
mosquitto_sub -h 192.168.1.33 -t "#" -p 36669 -u hisenseservice -P multimqttservice --debug
```

It may just be that your model does not require authorization, there is a similar issue in the dependency: https://github.com/newAM/hisensetv/issues/5

Can you try another command, such as `hisensetv 192.168.1.33 --key up` or `hisensetv 192.168.1.33 --get volume` and let me know if it works?

**Comment by sebasjunca** [comment]
@newAM Thanks for your reply. Apparently the authentication I made first with the mac was also valid for the RPI (Although I don't really understand why, I though It was like the Remote App with an independent authentication per connection) because when I run another command such as volume, menu or other it works fine.

The only issue I've been having is with the switch and updating the status. 10 - 15 seconds after I turn on the TV the switch goes back to off position (the tv stays on, is just the switch). This means that when I want to turn off the TV I have to torn on the switch and then turn it off to make it work.

**Comment by newAM** [comment]
> Apparently the authentication I made first with the mac was also valid for the RPI (Although I don't really understand why, I though It was like the Remote App with an independent authentication per connection) 

The MQTT server uses the MAC of your device to identify your device; the MAC is sent as part of the topic as a string.  This is just meaningless security through obscurity;  this implementation just bypasses this by using the same MAC to make it work across multiple clients after you authenticate once.

> The only issue I've been having is with the switch and updating the status. 10 - 15 seconds after I turn on the TV the switch goes back to off position (the tv stays on, is just the switch). This means that when I want to turn off the TV I have to torn on the switch and then turn it off to make it work.

Yeah, this specific implementation pings the TV to see if it is on or off; and it is slow to update.  This should be fixable.

**Comment by sebasjunca** [comment]
Great! Seems clear enough and a good approach to simplify all the config required (Certificates, TLS and more that I've seen needed to make MQTT work). Hope to see someday an update with the status. Thanks mate for all the work!

**Comment by newAM** [comment]
I updated the library, and this component to support TVs without SSL.  The branch is [issue-3](https://github.com/newAM/hisensetv_hass/tree/issue-3).

Can you test this out and let me know if it works?

**Comment by sebasjunca** [comment]
Sure, I'll give a try and let you know!

**Comment by sebasjunca** [comment]
I've replaced the content of custom_components with issue-3 and updated configuration.yaml with ssl: true. The command line still works, but HASS is not showing the switch now. Can't tell if is related to the new ssl attribute or if I'm missing a step in order to try issue-3. I installed the master through HACS though.

**Comment by newAM** [comment]
Might be related to #4 , I see `SwitchDevice is deprecated, modify HisenseTvEntity to extend SwitchEntity`.  That should not cause any breakage as far as I know, but I'll update that anyway.
